Remove-Item -Recurse -Force "c:/temp/Weave-Build"
New-Item -Type Directory -Force -Path "c:/temp/Weave-Build/Clean"
Compress-Archive -Path "../Weave" -DestinationPath "c:/temp/Weave-Build/Weave_demo.zip"
Copy-Item -Recurse -Path "../Weave" -Destination "c:/temp/Weave-Build/Clean"
Remove-Item -Recurse -Force "c:/temp/Weave-Build/Clean/Weave/Applications/*"
Remove-Item -Recurse -Force "c:/temp/Weave-Build/Clean/Weave/Contacts/*"
Remove-Item -Recurse -Force "c:/temp/Weave-Build/Clean/Weave/Meetings/*"
Remove-Item -Recurse -Force "c:/temp/Weave-Build/Clean/Weave/Daily/*"
Remove-Item -Force "c:/temp/Weave-Build/Clean/Weave/Getting Started.md"
Compress-Archive -Path "c:/temp/Weave-Build/Clean/Weave" -DestinationPath "c:/temp/Weave-Build/Weave_clean.zip"
Write-Host "Packages Built!"